package sqltojava;
import java.sql.ResultSet;
import Functions.Functions;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

public class srcEmpleados extends javax.swing.JFrame {

    DefaultTableModel modelo;
    Functions db = new Functions();    
    
    private ResultSet resultado;
    public srcEmpleados() {
        db.setCredentials(SQLtoJava.user, SQLtoJava.pass);
        initComponents();
        String[] titulos = {"ID", "Nombre", "Apellido Paterno", "Apellido Materno", "Domicilio", "RFC", "NSS"};
        modelo = new DefaultTableModel(null, titulos);
        tblEmpleado.setModel(modelo);
        dataEmpleados();
    }
    public void dataEmpleados() {
        try {
            resultado = db.consultaEmpleado();
            while(resultado.next()) {
                Object[] Usuario = {resultado.getString("idEmpleado"), resultado.getString("nombre"), resultado.getString("appat"), resultado.getString("apmat"), resultado.getString("domicilio"), resultado.getString("rfc"), resultado.getString("nss")};
                modelo.addRow(Usuario);
            }
            db.desconectar();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleado = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblApPat = new javax.swing.JLabel();
        txtApPat = new javax.swing.JTextField();
        lblApMat = new javax.swing.JLabel();
        txtApMat = new javax.swing.JTextField();
        lblDomicilio = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        lblRfc = new javax.swing.JLabel();
        txtRfc = new javax.swing.JTextField();
        lblNss = new javax.swing.JLabel();
        txtNss = new javax.swing.JTextField();
        lblIdEmpleado = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        tglEstado = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 680, 250));

        lblNombre.setText("Nombre del Empleado");
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 190, -1));

        lblApPat.setText("Apellido Paterno");
        jPanel1.add(lblApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));
        jPanel1.add(txtApPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, -1));

        lblApMat.setText("Apellido Materno");
        jPanel1.add(lblApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        jPanel1.add(txtApMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 190, -1));

        lblDomicilio.setText("Domicilio");
        jPanel1.add(lblDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));
        jPanel1.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 320, -1));

        lblRfc.setText("R. F. C.");
        jPanel1.add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        txtRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcActionPerformed(evt);
            }
        });
        jPanel1.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 140, -1));

        lblNss.setText("N. S. S.");
        jPanel1.add(lblNss, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));
        jPanel1.add(txtNss, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 140, -1));

        lblIdEmpleado.setText("ID Empleado");
        jPanel1.add(lblIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtIdEmpleado.setEditable(false);
        jPanel1.add(txtIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, -1));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        tglEstado.setText("Inactivo");
        tglEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(tglEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcActionPerformed

    private void tblEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadoMouseClicked
        DefaultTableModel model = (DefaultTableModel)tblEmpleado.getModel();
        int fila = tblEmpleado.getSelectedRow();
        
        txtIdEmpleado.setText(model.getValueAt(fila, 0).toString());
        txtNombre.setText(model.getValueAt(fila, 1).toString());
        txtApPat.setText(model.getValueAt(fila, 2).toString());
        txtApMat.setText(model.getValueAt(fila, 3).toString());
        txtDomicilio.setText(model.getValueAt(fila, 4).toString());
        txtRfc.setText(model.getValueAt(fila, 5).toString());
        txtNss.setText(model.getValueAt(fila, 6).toString());
        
        // obtener estado
        tglEstado.setEnabled(true);
        if (db.obtenerEstado(model.getValueAt(fila,0).toString())) {
            tglEstado.setText("Activo");
            tglEstado.setSelected(true);
        } else {
            tglEstado.setText("Inactivo");
            tglEstado.setSelected(false);
        }
    }//GEN-LAST:event_tblEmpleadoMouseClicked

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        db.updateEmpleado(txtIdEmpleado.getText(), txtNombre.getText(), txtApPat.getText(), txtApMat.getText(), txtDomicilio.getText(), txtRfc.getText(), txtNss.getText());
        modelo.setRowCount(0);
        dataEmpleados();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void tglEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglEstadoActionPerformed
        if (tglEstado.isSelected()) {
            tglEstado.setText("Activo");
            db.actualizarEstado(txtIdEmpleado.getText(), "1");
        } else {
            tglEstado.setText("Inactivo");
            db.actualizarEstado(txtIdEmpleado.getText(), "0");
        }   
    }//GEN-LAST:event_tglEstadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(srcEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(srcEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(srcEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(srcEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new srcEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblApMat;
    private javax.swing.JLabel lblApPat;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblIdEmpleado;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNss;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JTable tblEmpleado;
    private javax.swing.JToggleButton tglEstado;
    private javax.swing.JTextField txtApMat;
    private javax.swing.JTextField txtApPat;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNss;
    private javax.swing.JTextField txtRfc;
    // End of variables declaration//GEN-END:variables
}
